const el = id => document.getElementById(id); let folder = '';
const metrics = (files = '—', threats = '—', review = '—') => { el('files').textContent = files; el('threats').textContent = threats; el('review').textContent = review; };
function findings(items) { const list = el('list'); list.replaceChildren(); if (!items.length) { list.textContent = 'No confirmed threats or review items found.'; list.className = 'empty'; return; } list.className = ''; for (const item of items) { const row = document.createElement('div'); row.className = 'finding'; const tag = document.createElement('span'); tag.className = `badge ${item.severity}`; tag.textContent = item.severity === 'threat' ? 'DETECTED' : item.severity.toUpperCase(); const copy = document.createElement('div'); const title = document.createElement('b'); title.textContent = item.detection?.name ?? item.reason; const path = document.createElement('p'); path.textContent = item.file; copy.append(title, path); row.append(tag, copy); list.append(row); } }
el('choose').addEventListener('click', async () => { folder = await window.guard.chooseFolder() || folder; el('folder').value = folder; el('start').disabled = !folder; });
el('start').addEventListener('click', async () => { if (!folder) return; el('start').disabled = true; el('choose').disabled = true; el('status').textContent = 'Scanning local files'; el('detail').textContent = 'Hashing files and checking confirmed cloud intelligence.'; metrics('0', '0', '0'); try { const report = await window.guard.startScan(folder); const threats = report.findings.filter(x => x.severity === 'threat').length; const review = report.findings.filter(x => x.severity === 'review').length; metrics(report.filesScanned.toLocaleString(), threats, review); el('status').textContent = threats ? 'Threats detected' : 'Scan complete'; el('detail').textContent = threats ? 'Review confirmed detections below.' : 'No confirmed threats were found.'; findings(report.findings); } catch (error) { el('status').textContent = 'Scan unavailable'; el('detail').textContent = error.message; } finally { el('start').disabled = false; el('choose').disabled = false; el('progress').textContent = ''; } });
window.guard.onProgress(({ completed, total }) => { el('progress').textContent = `${completed.toLocaleString()} / ${total.toLocaleString()} files`; el('files').textContent = completed.toLocaleString(); });
const dialog = el('settingsDialog'); el('settings').addEventListener('click', async () => { el('endpoint').value = (await window.guard.getSettings()).endpoint; dialog.showModal(); });
el('saveSettings').addEventListener('click', async event => { event.preventDefault(); try { await window.guard.saveSettings({ endpoint: el('endpoint').value }); dialog.close(); } catch (error) { el('endpoint').setCustomValidity(error.message); el('endpoint').reportValidity(); } });
const update = el('update'), updateText = el('updateText'), updateAction = el('updateAction');
function showUpdate(text, action, handler) { update.hidden = false; updateText.textContent = text; updateAction.hidden = !action; updateAction.textContent = action || ''; updateAction.onclick = handler || null; }
el('checkUpdates').addEventListener('click', async () => { const result = await window.guard.checkUpdates(); if (!result.supported) showUpdate('Updates are checked in installed builds.', null); else showUpdate('Checking for updates…', null); });
window.guard.onUpdate(({ event, version, percent, message }) => { if (event === 'checking') showUpdate('Checking for updates…', null); if (event === 'current') showUpdate('Sharco Guard is up to date.', null); if (event === 'available') showUpdate(`Version ${version} is available.`, 'Download update', () => window.guard.downloadUpdate()); if (event === 'downloading') showUpdate(`Downloading update: ${Math.round(percent)}%`, null); if (event === 'downloaded') showUpdate(`Version ${version} is ready.`, 'Restart and install', () => window.guard.installUpdate()); if (event === 'error') showUpdate(`Update check unavailable: ${message}`, null); });
